### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by benwurth** [teamTALIMA/teamTALIMA_theGAME#1]
It would be great if you could let team members know how to set up and run their own version of BeastieBot. A good place to do this is in a README.md file in the root of your repository. The contents of the file will be displayed right on the repository's page on Github.

You can find out more about how to format your Readme [here](https://guides.github.com/features/mastering-markdown/).

(While you're at it, you might want to add a set of contributing guidelines, as well as a file that lets users know what license you're releasing your file under)

**Comment by TalimaVale** [comment]
Finally did it!
