### ISSUE TITLE
Asset Serialization should be set to Force Text

### ISSUE THREAD

**Issue by blind** [teamTALIMA/teamTALIMA_theGAME#6]
To be able to merge assets stored in git (or any VCS really) the asset serialization should be force to text, since git is made to handle text files. This should preferably be done _before_ importing the project to git. :kappa:

You can find the setting under Edit -> Project Settings -> Editor

**Comment by benwurth** [comment]
This addresses the same problem as issue #5. Though both can be done, of course.

**Comment by blind** [comment]
It really doesn't. Force Text on assets will make scenes and prefabs mergeable, and help a lot if there is more than one developer modifying assets. git-lfs is just a better way to store big binary files, it will not help at all for issues when merging.

**Comment by benwurth** [comment]
Gotcha. I misread your first comment. Sounds good to me!

**Comment by scryptonite** [comment]
Closing since Talima committed the fix in f88fb3c14203cad6d010fa6990d8ca8b38568c85 a while back 😄 

Thank you for filing the issue @blind! Now the diffs for the commits to Unity assets are much more human (& git) friendly. 👍 

--------------

> Asset Serialization changed to 'Force Text' 
> &mdash; @teamTALIMA / f88fb3c14203cad6d010fa6990d8ca8b38568c85
